### ISSUE TITLE
Node.js Live L.A. - Docker for Node.js

### ISSUE THREAD

**Issue by dshaw** [nodejs/live.nodejs.org#13]
Abstract:

**Docker for Node.js**
by Dan Shaw, CTO and Co-Founder of NodeSource

NodeSource maintains hundreds of unique platform Docker images of Node.js across linux distribution platforms and versions and Node.js versions. These are used as base images for Enterprise Node.js users and as an official service for NodeSource N|Support customers. We will share how we manage and test across all these permutations and why NodeSource recently dropped automated builds on Docker Hub.

Headshot, if needed: https://nodesource.com/resources/presskit/nodesource/headshot-dshaw.jpg

**Comment by mikeal** [comment]
Accepted.
