### ISSUE TITLE
NodeJs Bangalore talk on Adonis Js

### ISSUE THREAD

**Issue by thetutlage** [nodejs/live.nodejs.org#17]
**Location**: Bangalore
**Title**: Writing maintainable apps with Adonis Js
**Description** :

Adonis Js is a different breed of framework in NodeJs. It follows some great concepts of Dependency Injection and leverages the full power of ES6 by using **Proxies, ES6 generators** etc.

Topics to be covered.
1. Why AdonisJs?
2. New way to inject dependencies and writing testable code
3. What the heck are ES6 proxies?

**Comment by mikeal** [comment]
Accepted.

Also, if you know anyone else that would like to speak tell them to submit, we'd love some more talk proposals :)

**Comment by thetutlage** [comment]
@mikeal Thanks

What is the next step?
