### ISSUE TITLE
Programming best practices: Memory efficiency with Closures

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/live.nodejs.org#18]
Session proposal for Bangalore.

Memory Leaks leading to undesired growth and exhaustion of memory are by far the most common production problem reported on enterprise scale Node applications. Closures, a powerful semantic feature in functional programs which are used pervasively in Node.js/Javascript programs to support their asynchronous and event driven programming model, are a prominent source of unanticipated memory leaks.

In this presentation, I will explain three of the most common use cases where Closures are used in Node. For each of the use cases, I will explain a) sample code, b) the life-span of the Closure context and which variables the closure keeps live, iii) what memory will be retained during the life-span of the Closure. The intention is to help the audience better understand the execution environment of Closures, their implications to memory footprint, and help them develop efficient code.

**Comment by mikeal** [comment]
Accepted.

Also, if you know anyone else that would like to speak tell them to submit, we'd love some more talk proposals :)

**Comment by gireeshpunathil** [comment]
thank you. sure, will do.
