### ISSUE TITLE
Node.js Community Benchmarking Efforts (Paris)

### ISSUE THREAD

**Issue by gareth-ellis** [nodejs/live.nodejs.org#23]
Benchmarks and the information they provide are important to ensure that changes going into Node.js don't regress key attributes like startup speed, memory footprint and throughput. Come and hear about some of the fundamentals of benchmarking, how to go about narrowing down the cause of a regression between versions of node along with the efforts underway in the community benchmarking workgroup (https://github.com/nodejs/benchmarking) to run/capture/report and act on benchmark information.

**Comment by hackygolucky** [comment]
@gareth-ellis This is great! A few questions:
1. I noticed you're based in Hursley. We are unable to provide travel budget for this event. Will this be a deterrent from you being able to speak?
2. Do you have a further hashed out story that helps convey how we learn this info in 30 minutes? I think this is a valuable topic for our community members to hear about.

**Comment by gareth-ellis** [comment]
@hackygolucky 
Yes - I'm hoping to get travel approval, so it should not be an issue.

Will post fleshed out bit very shortly

**Comment by hackygolucky** [comment]
awesome! Thanks Gareth.
