### ISSUE TITLE
Node JS Bangalore talk on Secure Scalable NodeJS

### ISSUE THREAD

**Issue by Niranjan-J007** [nodejs/live.nodejs.org#25]
Location: Bangalore
Title: Secure Scalable NodeJS for Enterprise
Description :
Kraken is a secure and scalable layer that extends nodejs by providing structure and convention. It also supports private NPM for enterprise.

Topics to be covered.
NodeJS & security
Npm & private hosting
Internationalization support

**Comment by mikeal** [comment]
Accepted.

Could you send me your email address?

**Comment by mikeal** [comment]
@Niranjan-J007 can you email vishal.chandra@wipro.com with your speaker details ;)
