### ISSUE TITLE
Functional node [bangalore-proposal]

### ISSUE THREAD

**Issue by coco98** [nodejs/live.nodejs.org#26]
This is a loose outline. I will refine over the coming days, esp. based on feedback!

**Topics:**
- "Functional programming": A quick overview
- Node/JS features that makes functional programming possible
- ES6 syntax that make functional thinking easier
- Common procedural paradigms translated to functional style (loops, modularising/encapsulation, callbacks, global variables converted to functional equivalents)
- React + Redux: real world example of functional paradigms and dataflow

**Comment by anirudh24seven** [comment]
+1

It would also be good to know the differences between working with React + Redux and working with Javascript libraries like fn.js and Underscore.js

**Comment by ecthiender** [comment]
+1

I would be interested in NodeJS/JavaScript features + ES6 syntax for functional programming.

**Comment by rohangeorge91** [comment]
+1

Hmm... I like to know more on es6 (lot of hype on this...so), the design paradigm and it's application in making functional programming on a nodejs web server... Basically I write a lot of node based web-servers and would like to know the pros/cons in making webapps using functional programming.

**Comment by balajirrao** [comment]
+1

I would like to learn about ES6 syntax and React + Redux.

**Comment by nullxone** [comment]
:+1: +1 Would attend this
