### ISSUE TITLE
Instrumenting Node.js in production (Paris)

### ISSUE THREAD

**Issue by watson** [nodejs/live.nodejs.org#28]
This talk covers different approaches of instrumenting a Node.js application. If applied correctly, instrumentation will allow you to discover bottlenecks or track and log application usage - even in production, without sacrificing performance.

Part one will cover the current state of tracing and instrumentation. In part two we’ll take a look at the next-gen core tracing API's being developed under the Node.js Tracing Working Group.

**Comment by hackygolucky** [comment]
Howdy @watson. I think this talk would be great for the community to hear in Paris. A few questions:
1. We are unable to provide travel budget for this event. Would this deter you from speaking?
2. The talk will be 30 minutes. Can you elaborate a little more how you would cover both pieces of this story in that time frame?

**Comment by watson** [comment]
> We are unable to provide travel budget for this event. Would this deter you from speaking?

Not at all. I would be attended no matter what.

> The talk will be 30 minutes. Can you elaborate a little more how you would cover both pieces of this story in that time frame?

I’m still working out the details of the talk, and if it ends up getting too cramped to cover both things in detail, I might just quickly give an overview of the current state to set the stage and concentrate on what's coming to Node core soon.
