### ISSUE TITLE
SailsJS realtime and API driven (MVC NodeJS) framework introduction [Bangalore]

### ISSUE THREAD

**Issue by Nishchit14** [nodejs/live.nodejs.org#29]
**Location**: Bangalore
**Title**:  SailsJS, a realtime & API first framework for beginners introduction.
**Description** :

Sails is built on [Node.js](https://nodejs.org/en/), uses [Express](http://expressjs.com/) for handling HTTP requests, and wraps [socket.io](http://socket.io/) for managing WebSockets.

**List of topics:** _proposal_
- What is SailsJS ?
- Concept of sailsjs (architecture).
- Use of waterline & wa adapters.
- API routing and Real-time sockets example.
-  familiarity (mvc, EJS is like erb/jsp/etc)
- the advantages of node.js itself
- compatibility with any front end strategy
-  usable with any npm package, and optionally standardized with machinepacks, plus a number of higher level plugin systems 
- the virtual request interpreter 
- database agnosticism

Permission by **[Mike McNeil](https://twitter.com/mikermcneil)**, creator of [SailsJS](http://sailsjs.org/).

**Comment by ycpatel813** [comment]
:+1:  I will surely attend.

**Comment by viral1030** [comment]
Woooo!  :+1:

**Comment by Nishchit14** [comment]
@all 

description updated
