### ISSUE TITLE
API Publishing with Node.js (Beijing)

### ISSUE THREAD

**Issue by shiya** [nodejs/live.nodejs.org#32]
I'd like to give a talk on some aspects of API publishing/management using Node.js. Working for a company that publishes APIs that comes from many business models(Autodesk), organizing APIs to publish to internal and third party developers to consume was a big task. We have been heavily dependent on some great features of Node.js to streamline the process.
I thought it'd be nice to share with others about my finding and generate some discussions so we can learn from others too.

Here's an outline of what it's going to be about:
- What are APIs and why they're important to companies
- Why Node.js is the best technology for working with REST APIs
  - Internal tools
  - Sample code
- The process of bringing APIs from different services and different languages all in one developer portal
- Best practices, what worked for us, what didn't
- Explorations on using npm packages as SDKs

**Comment by xeodou** [comment]
Hi @shiya Would you like submit a proposal for 2016.jsconf.cn , we really want femal JavaScript developers in China can get more invoved in the comunity. At 2015 we even didn't have one female speaker, that's shame on us. So this year, i'm telling myself, what ever we do we need girls know the conferences and give a talk on the conferences.

**Comment by hackygolucky** [comment]
@xeodou @shiya perhaps y'all could chat more about this at the Node Live event? I'll be at the event as well and I'd love to talk to you more about how the Foundation can help with strategies around improving diversity and inclusivity at your event.

I also highly recommend reaching out to the Node.js Inclusivity Working Group. There's a lot of folks brimming with knowledge and very friendly. https://github.com/nodejs/inclusivity#inclusivity-working-group

**Comment by shiya** [comment]
Hey @xeodou I am actually planning to submit a proposal for NingJS. I have some very interesting JavaScript topics to talk about. Thank you for welcoming me to apply.
@hackygolucky I want to check out the Inclusivity Working Group too & see if I can bring anything to the table... 
See you guys at the Node Live event!

**Comment by xeodou** [comment]
Thanks for your advice @hackygolucky 
@shiya  That's awesome.  
We can talk more when we met in Beijing @shiya @hackygolucky
