### ISSUE TITLE
Theme: Node.js Full Stack Development Scheme for Mobile Ends

### ISSUE THREAD

**Issue by rachel4869** [nodejs/live.nodejs.org#35]
Abstract: 
The JavaScript-based Full Stack development mode has been getting increasingly popular. The development of mobile Apps is in large demand, so a Node.js full stack development scheme covering mobile ends is of great importance. 
1. How to perform cloud-end integrated product development mode based on Node.js, including Apps at the mobile end and services at the server end, and operate the same data model at the front and back ends to implement one-to-one mapping between data objects at the front end and data sources at the back end?
2. How to encapsulate different types of data sources (databases and third party services) into a standard data model based on Node.js according to service requirements, and what are the encapsulation rules?
3. How to enable an encapsulated data model to automatically generate APIs with different formats through model definition and configuration based on the requirements of different services?
4. How to define and use functional extension objects for mobile ends based on the extension standards of Node.js?

**Comment by hackygolucky** [comment]
Howdy @rachel4869, which Node.js Live location would you like this considered for?

**Comment by rachel4869** [comment]
Beijing

**Comment by hackygolucky** [comment]
Education Community Manager here!

We are going to be doing a lightning round of talks at Node Live Beijing, and if you're still available to speak and will be on May 21, we would love to see you give your talk in a condensed 15 minute slot. 

If you are interested, I would need a 1-2 sentence bio about you and a shortened summary of your talk.

Thanks.
