### ISSUE TITLE
A secure and scalable SSO gateway with Node.js for millions of users in China (Beijing)

### ISSUE THREAD

**Issue by xeodou** [nodejs/live.nodejs.org#39]
Hey, there

I'm Xeodou Li, senior backend engineer at [Wiredcraft](http://wiredcraft.com).

My proposed talk, is **about building and shipping a secure and scalable SSO(single sign-on) gateway with Node.js for millions of users in China**.

Working with a Fortune 500 F&B company, me and my team have been in charge of taking over a complex architecture, including many moving pieces that support Web, mobile and backend applications used by millions of users in China (both consumers and stakeholders).

One of the crucial pieces of our service oriented architecture was authentication; we needed to build a fast, secure and scalable system that allowed not only to authenticate users across all apps (Android, iOS and Web) and secure all requests to backend systems.

In doing so, we learned many things about building and scaling a secure SSO solution. I'll share our journey and insights.

And i'm apply the Node.JS event in Beijing. 

Best 

Thanks.

**Comment by hackygolucky** [comment]
Education Community Manager here!

We are going to be doing a lightning round of talks at Node Live Beijing, and if you're still available to speak and will be on May 21, we would love to see you give your talk in a condensed 15 minute slot.

If you are interested, I would need a 1-2 sentence bio about you and a shortened summary of your talk.

Thanks.
