### ISSUE TITLE
Rethinking Package Management in Node.js - London

### ISSUE THREAD

**Issue by alexanderGugel** [nodejs/live.nodejs.org#45]
I would like to give a talk on some of the challenges faced when writing a package manager for Node.js. My goal is to discuss radically different approaches to package management. Here is a quick summary of what I want to talk about:
1. Efficient package management: Alternative installation strategies and performance optimizations
2. Alternative installation strategies: Beyond central registries
3. Writing a minimal package manager: How to write a npm clone in ~ 200 LoC
4. Why Node.js is different: The difficulties of supporting circular dependencies
5. Better shrinkwrapping

I'm the author of [ied](https://github.com/alexanderGugel/ied), an alternative package manager for Node.js, which tries to solve some of the issues that I'm about to talk about at this event (at least that's what I hope :)). I feel like I learned a lot while working on this project, which I think is worth sharing.

My goal is **not** to promote ied or to rant about npm, but rather to discuss various approaches to package management.

**Comment by antonsamper** [comment]
👍

**Comment by ddolheguy** [comment]
👍

**Comment by nowtvicebergteam** [comment]
👍
