### ISSUE TITLE
Avoiding Release Paralysis - London

### ISSUE THREAD

**Issue by sublimino** [nodejs/live.nodejs.org#57]
Continuous Deployment is a powerful vehicle to carry code to production. It promises quick, frequent, and well-tested releases with zero-downtime deployment, decoupled services, and an end to fallible manual testing.

But every solution is a compromise, and the complexity of CD can dissuade risk-averse teams. In this talk, we describe lessons learned in continuously deploying Node.js applications in Docker at major UK media and energy corporations, and how those lessons can be applied to teams of any size.

This talk uses a distributed Node.js example application to demonstrate: 
- CI/testing best practices
- debugging and system acceptance testing locally before CI
- provisioning and deploying cloud-agnostic infrastructure
- continuously testing and deploying an application
- how to fix CD when it breaks.

**Comment by cdnadmin** [comment]
@sublimino , please correct me if I have the wrong URL or there is a more appropriate one.  But, [this is the talk](https://www.binarysludge.com/2016/05/12/avoiding-release-paralysis/), yes?

**Comment by sublimino** [comment]
@cdnadmin that's it, yes :)
