### ISSUE TITLE
SAGE2: Local and distributed collaboration on large displays - Chicago

### ISSUE THREAD

**Issue by renambot-uic** [nodejs/live.nodejs.org#61]
If you need a local speaker from Chicago, I could talk about our research project at the Electronic Visualization Lab at UIC (University of Illinois at Chicago) and the experience of using Nodejs as a backend for collaboration and data visualization.

A Scalable Resolution Display Environments can be any configuration of displays, ranging from a single monitor to a wall of tiled flat-panel displays. SAGE2 creates a seamless ultra-high resolution desktop across the wall. Users can wirelessly connect to the wall with their own devices in order to interact with the system. Many users can simultaneously utilize a drag-and-drop browser interface to transfer local documents and show them on the wall, use a mouse pointer and keyboard to interact with existing content that is on the wall and share their screen so that it is viewable to all. SAGE2 can be used in many configurations and is able to support many communities working with various types of media and high-resolution content, from research meetings to creative session to education. Being browser-based, data visualization applications can be created quickly using 3rd party library such as D3.js, Snap, Vega, WebGL,... and be integrated into the SAGE2 API. The SAGE2 server, based on Nodejs, uses Websockets for data sharing and synchronization between all the clients.

Introduction to SAGE2 (Scalable Amplified Group Environment) video:
https://youtu.be/V9zGmQpaRUU?t=32s

**Comment by hackygolucky** [comment]
This sounds really neat! If you're still available, i'll need a 1-2 sentence bio from you and also a shorter summary of this talk for the website.

**Comment by renambot-uic** [comment]
> On Jun 9, 2016, at 9:46 PM, Tracy notifications@github.com wrote:
> 
> This sounds really neat! If you're still available, i'll need a 1-2 sentence bio from you and also a shorter summary of this talk for the website.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thank.

Would this be OK ?

Luc Renambot is a Research Associate Professor of Computer Science at the University of Illinois at Chicago. His research at the Electronic Visualization Laboratory focuses on interaction and collaboration using advanced visualization displays and high-speed networking.

SAGE2 is a Node.js and browser-based environment that creates a seamless ultra-high resolution desktop across display wall (one to many displays). Users can wirelessly connect to the wall to interact with the system, transfer documents, manipulate applications and share their screen. Data visualization applications can be created quickly using 3rd party library such as D3.js, Snap, Vega, WebGL, and be integrated into the SAGE2 API.
We will present our experience using Nodejs for this academic research environment.

Luc

**Comment by hackygolucky** [comment]
👍
