### ISSUE TITLE
Get Atlanta on the Schedule?

### ISSUE THREAD

**Issue by atonb117** [nodejs/live.nodejs.org#75]
Hi, all.

Just learned about this and was wondering how we can get Atlanta, GA on the schedule later this year or early next year?

We have a great developer community here and many students.

**Comment by hackygolucky** [comment]
Howdy @atonb117 

We've locked in the schedule for the remainder of 2016, but we'll keep this in mind for the 2017 schedule when we are discussing what places we'll be visiting if we do continue the Node Live tour into 2017.

**Comment by atonb117** [comment]
Cool, thanks.  Should tag this as potential 2017 location.
