### ISSUE TITLE
Event registration form broken

### ISSUE THREAD

**Issue by Krinkle** [nodejs/live.nodejs.org#79]
Browser: Chrome 51.0.2704.103 stable (also reproducible with Chrome 53.0.2785.0 canary).
1. http://live.nodejs.org/events/london.html
2. https://www.regonline.com/Register/Checkin.aspx?EventID=1813427
3. Enter e-mail address, leave London option selected, press Continue.

**Actual result**
The form submits to Checkin.aspx, then 302 redirects to PersonalInfo.aspx, then 302 redirects to Error.aspx

> An unexpected system error has occurred.
> We apologize for this inconvenience. Please try the following:
> Click the browser's Back button and try again.
> Close and restart the browser and try again.
> Error ID:fc1f3592-ec26-4bf5-b1ce-29f9b4ab4fd8

<img width="634" alt="screen shot 2016-07-02 at 23 21 46" src="https://cloud.githubusercontent.com/assets/156867/16542715/c930366a-40ab-11e6-95f3-e19cb052759b.png">

PS: It seems to be working fine in Firefox, however.

**Comment by hackygolucky** [comment]
It's possible the RegOnline form was acting up because we'd closed the reg. Thanks for reporting this and I'm sorry you had trouble.

**Comment by Krinkle** [comment]
@hackygolucky This was 23 days ago.

The bug still exists on current events. For example, when trying to register for Boston:
1. http://live.nodejs.org/events/boston.html
2. Register now, https://www.regonline.com/Register/Checkin.aspx?EventID=1813427
3. Enter e-mail address.
4. Press Continue.

<img width="475" alt="screen shot 2016-07-25 at 20 14 36" src="https://cloud.githubusercontent.com/assets/156867/17113865/6dc6b366-52a4-11e6-8bd3-619d08a48393.png">

<img width="853" alt="screen shot 2016-07-25 at 20 14 22" src="https://cloud.githubusercontent.com/assets/156867/17113850/653a43b6-52a4-11e6-92eb-71bb5ba02308.png">
